databases:
  - name: shivani
    databaseName: shivani_pzf6
    user: shivani_pzf6_user
    plan: free

services:
  - type: web
    name: shivani
    runtime: ruby
    plan: free
    buildCommand: "npm run build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shivani_pzf6
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default